import 'package:yosrixia/core/models/word_model.dart';

Map<String, Map<String, List<WordModel>>> arabicCharactersMap = {
  'أ': {
    'أَ': [
      WordModel(
        wordToDisplay: 'أَرنب',
        wordToCheck: 'ارنب',
        imagePadding: 50.0,
        imagePath: 'assets/images/characters/alef/alef1Arnab.png',
        voicePath: 'images/characters/alef/alef1Arnab.wav',
      ),
      WordModel(
        wordToDisplay: 'مدفأَة',
        wordToCheck: 'مدفاه',
        imagePadding: 0,
        imagePath: 'assets/images/characters/alef/alef1Medfaah.png',
        voicePath: 'images/characters/alef/alef1Medfaah.wav',
      ),
      WordModel(
        wordToDisplay: 'أَسد',
        wordToCheck: 'اسد',
        imagePadding: 0,
        imagePath: 'assets/images/characters/alef/alef1Asad.png',
        voicePath: 'images/characters/alef/alef1Asad.wav',
      ),
      WordModel(
        wordToDisplay: 'أَقلام',
        wordToCheck: 'اقلام',
        imagePadding: 0,
        imagePath: 'assets/images/characters/alef/alef1Aqlaam.png',
        voicePath: 'images/characters/alef/alef1Aqlaam.wav',
      ),
      WordModel(
        wordToDisplay: 'أَسنان',
        wordToCheck: 'اسنان',
        imagePadding: 0,
        imagePath: 'assets/images/characters/alef/alef1Asnan.png',
        voicePath: 'images/characters/alef/alef1Asnan.wav',
      ),
      WordModel(
        wordToDisplay: 'أَشجار',
        wordToCheck: 'اشجار',
        imagePadding: 0,
        imagePath: 'assets/images/characters/alef/alef1Ashjaar.png',
        voicePath: 'images/characters/alef/alef1Ashjaar.wav',
      ),
    ],
    'إِ': [
      WordModel(
        wordToDisplay: 'إِبره',
        wordToCheck: 'ابره',
        imagePadding: 0,
        imagePath: 'assets/images/characters/alef/alef2Ibrah.png',
        voicePath: 'images/characters/alef/alef2Ibrah.wav',
      ),
      WordModel(
        wordToDisplay: 'إِنسان',
        wordToCheck: 'انسان',
        imagePadding: 0,
        imagePath: 'assets/images/characters/alef/alef2Insan.png',
        voicePath: 'images/characters/alef/alef2Insan.wav',
      ),
      WordModel(
        wordToDisplay: 'إِصبع',
        wordToCheck: 'إِصبع',
        imagePadding: 0,
        imagePath: 'assets/images/characters/alef/alef2Isba.png',
        voicePath: 'images/characters/alef/alef2Isba.wav',
      ),
      WordModel(
        wordToDisplay: 'إِبريق',
        wordToCheck: 'ابريق',
        imagePadding: 0,
        imagePath: 'assets/images/characters/alef/alef2Ibreeq.png',
        voicePath: 'images/characters/alef/alef2Ibreeq.wav',
      ),
      WordModel(
        wordToDisplay: 'عائد',
        wordToCheck: 'عائد',
        imagePadding: 100,
        imagePath: 'assets/images/characters/alef/alef2Aaid.png',
        voicePath: 'images/characters/alef/alef2Aaid.wav',
      ),
      WordModel(
        wordToDisplay: 'صائم',
        wordToCheck: 'صائم',
        imagePadding: 0,
        imagePath: 'assets/images/characters/alef/alef2Saim.png',
        voicePath: 'images/characters/alef/alef2Saim.wav',
      ),
    ],
    'أُ': [
      WordModel(
        wordToDisplay: 'أُخطبوط',
        wordToCheck: 'اخطبوط',
        imagePadding: 0,
        imagePath: 'assets/images/characters/alef/alef3Ukhtboot.png',
        voicePath: 'images/characters/alef/alef3Ukhtboot.wav',
      ),
      WordModel(
        wordToDisplay: 'أُرجوحة',
        wordToCheck: 'ارجوحة',
        imagePadding: 0,
        imagePath: 'assets/images/characters/alef/alef3Urjooha.png',
        voicePath: 'images/characters/alef/alef3Urjooha.wav',
      ),
      WordModel(
        wordToDisplay: 'أُذن',
        wordToCheck: 'اذن',
        imagePadding: 0,
        imagePath: 'assets/images/characters/alef/alef3Udhun.png',
        voicePath: 'images/characters/alef/alef3Udhun.wav',
      ),
      WordModel(
        wordToDisplay: 'أُم',
        wordToCheck: 'ام',
        imagePadding: 0,
        imagePath: 'assets/images/characters/alef/alef3Um.png',
        voicePath: 'images/characters/alef/alef3Um.wav',
      ),
    ],
    'أْ': [
      WordModel(
        wordToDisplay: 'فأْس',
        wordToCheck: 'فاس',
        imagePadding: 0,
        imagePath: 'assets/images/characters/alef/alef4Faas.png',
        voicePath: 'images/characters/alef/alef4Faas.wav',
      ),
      WordModel(
        wordToDisplay: 'كأْس',
        wordToCheck: 'كاس',
        imagePadding: 0,
        imagePath: 'assets/images/characters/alef/alef4Kaas.png',
        voicePath: 'images/characters/alef/alef4Kaas.wav',
      ),
      WordModel(
        wordToDisplay: 'رأْس',
        wordToCheck: 'راس',
        imagePadding: 0,
        imagePath: 'assets/images/characters/alef/alef4Raas.png',
        voicePath: 'images/characters/alef/alef4Raas.wav',
      ),
      WordModel(
        wordToDisplay: 'فأْر',
        wordToCheck: 'فار',
        imagePadding: 0,
        imagePath: 'assets/images/characters/alef/alef4Faar.png',
        voicePath: 'images/characters/alef/alef4Faar.wav',
      ),
    ],
  },
};
