import 'package:yosrixia/core/models/word_model.dart';

Map<String, Map<String, List<WordModel>>> arabicCharactersMap = {
  'أ': {
    'أَ': [
      WordModel(
        wordToDisplay: 'أَرنب',
        wordToCheck: 'ارنب',
        imagePadding: 50.0,
        imagePath: 'assets/media/characters/alef/alef1Arnab.png',
        voicePath: 'media/characters/alef/alef1Arnab.wav',
      ),
      WordModel(
        wordToDisplay: 'مدفأَة',
        wordToCheck: 'مدفاه',
        imagePadding: 0,
        imagePath: 'assets/media/characters/alef/alef1Medfaah.png',
        voicePath: 'media/characters/alef/alef1Medfaah.wav',
      ),
      WordModel(
        wordToDisplay: 'أَسد',
        wordToCheck: 'اسد',
        imagePadding: 0,
        imagePath: 'assets/media/characters/alef/alef1Asad.png',
        voicePath: 'media/characters/alef/alef1Asad.wav',
      ),
      WordModel(
        wordToDisplay: 'أَقلام',
        wordToCheck: 'اقلام',
        imagePadding: 0,
        imagePath: 'assets/media/characters/alef/alef1Aqlaam.png',
        voicePath: 'media/characters/alef/alef1Aqlaam.wav',
      ),
      WordModel(
        wordToDisplay: 'أَسنان',
        wordToCheck: 'اسنان',
        imagePadding: 0,
        imagePath: 'assets/media/characters/alef/alef1Asnan.png',
        voicePath: 'media/characters/alef/alef1Asnan.wav',
      ),
      WordModel(
        wordToDisplay: 'أَشجار',
        wordToCheck: 'اشجار',
        imagePadding: 0,
        imagePath: 'assets/media/characters/alef/alef1Ashjaar.png',
        voicePath: 'media/characters/alef/alef1Ashjaar.wav',
      ),
    ],
    'إِ': [
      WordModel(
        wordToDisplay: 'إِبره',
        wordToCheck: 'ابره',
        imagePadding: 0,
        imagePath: 'assets/media/characters/alef/alef2Ibrah.png',
        voicePath: 'media/characters/alef/alef2Ibrah.wav',
      ),
      WordModel(
        wordToDisplay: 'إِنسان',
        wordToCheck: 'انسان',
        imagePadding: 0,
        imagePath: 'assets/media/characters/alef/alef2Insan.png',
        voicePath: 'media/characters/alef/alef2Insan.wav',
      ),
      WordModel(
        wordToDisplay: 'إِصبع',
        wordToCheck: 'اصبع',
        imagePadding: 0,
        imagePath: 'assets/media/characters/alef/alef2Isba.png',
        voicePath: 'media/characters/alef/alef2Isba.wav',
      ),
      WordModel(
        wordToDisplay: 'إِبريق',
        wordToCheck: 'ابريق',
        imagePadding: 0,
        imagePath: 'assets/media/characters/alef/alef2Ibreeq.png',
        voicePath: 'media/characters/alef/alef2Ibreeq.wav',
      ),
      WordModel(
        wordToDisplay: 'عائد',
        wordToCheck: 'عائد',
        imagePadding: 100,
        imagePath: 'assets/media/characters/alef/alef2Aaid.png',
        voicePath: 'media/characters/alef/alef2Aaid.wav',
      ),
      WordModel(
        wordToDisplay: 'صائم',
        wordToCheck: 'صائم',
        imagePadding: 0,
        imagePath: 'assets/media/characters/alef/alef2Saim.png',
        voicePath: 'media/characters/alef/alef2Saim.wav',
      ),
    ],
    'أُ': [
      WordModel(
        wordToDisplay: 'أُخطبوط',
        wordToCheck: 'اخطبوط',
        imagePadding: 0,
        imagePath: 'assets/media/characters/alef/alef3Ukhtboot.png',
        voicePath: 'media/characters/alef/alef3Ukhtboot.wav',
      ),
      WordModel(
        wordToDisplay: 'أُرجوحة',
        wordToCheck: 'ارجوحه',
        imagePadding: 0,
        imagePath: 'assets/media/characters/alef/alef3Urjooha.png',
        voicePath: 'media/characters/alef/alef3Urjooha.wav',
      ),
      WordModel(
        wordToDisplay: 'أُذن',
        wordToCheck: 'اذن',
        imagePadding: 0,
        imagePath: 'assets/media/characters/alef/alef3Udhun.png',
        voicePath: 'media/characters/alef/alef3Udhun.wav',
      ),
      WordModel(
        wordToDisplay: 'أُم',
        wordToCheck: 'ام',
        imagePadding: 0,
        imagePath: 'assets/media/characters/alef/alef3Um.png',
        voicePath: 'media/characters/alef/alef3Um.wav',
      ),
    ],
    'أْ': [
      WordModel(
        wordToDisplay: 'فأْس',
        wordToCheck: 'فاس',
        imagePadding: 0,
        imagePath: 'assets/media/characters/alef/alef4Faas.png',
        voicePath: 'media/characters/alef/alef4Faas.wav',
      ),
      WordModel(
        wordToDisplay: 'كأْس',
        wordToCheck: 'كاس',
        imagePadding: 0,
        imagePath: 'assets/media/characters/alef/alef4Kaas.png',
        voicePath: 'media/characters/alef/alef4Kaas.wav',
      ),
      WordModel(
        wordToDisplay: 'رأْس',
        wordToCheck: 'راس',
        imagePadding: 0,
        imagePath: 'assets/media/characters/alef/alef4Raas.png',
        voicePath: 'media/characters/alef/alef4Raas.wav',
      ),
      WordModel(
        wordToDisplay: 'فأْر',
        wordToCheck: 'فار',
        imagePadding: 0,
        imagePath: 'assets/media/characters/alef/alef4Faar.png',
        voicePath: 'media/characters/alef/alef4Faar.wav',
      ),
    ],
  },
  'ب': {
  'بَ': [
    WordModel(
      wordToDisplay: 'بَطه',
      wordToCheck: 'بطه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ba/ba1Bata.png',
      voicePath: 'media/characters/ba/ba1Bata.wav',
    ),
    WordModel(
      wordToDisplay: 'بَنجر',
      wordToCheck: 'بنجر',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ba/ba1Banjar.png',
      voicePath: 'media/characters/ba/ba1Banjar.wav',
    ),
    WordModel(
      wordToDisplay: 'بَقرة',
      wordToCheck: 'بقره',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ba/ba1Baqara.png',
      voicePath: 'media/characters/ba/ba1Baqara.wav',
    ),
    WordModel(
      wordToDisplay: 'بَطريق',
      wordToCheck: 'بطريق',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ba/ba1Batriq.png',
      voicePath: 'media/characters/ba/ba1Batriq.wav',
    ),
    WordModel(
      wordToDisplay: 'بَاب',
      wordToCheck: 'باب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ba/ba1Baab.png',
      voicePath: 'media/characters/ba/ba1Baab.wav',
    ),
    WordModel(
      wordToDisplay: 'بَيت',
      wordToCheck: 'بيت',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ba/ba1Bayt.png',
      voicePath: 'media/characters/ba/ba1Bayt.wav',
    ),
    WordModel(
      wordToDisplay: 'صبَاح',
      wordToCheck: 'صباح',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ba/ba1Sabaah.png',
      voicePath: 'media/characters/ba/ba1Sabaah.wav',
    ),
    WordModel(
      wordToDisplay: 'ربَاط',
      wordToCheck: 'رباط',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ba/ba1Ribaat.png',
      voicePath: 'media/characters/ba/ba1Ribaat.wav',
    ),
  ],
  'بِ': [
    WordModel(
      wordToDisplay: 'بِنت',
      wordToCheck: 'بنت',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ba/ba2Bint.png',
      voicePath: 'media/characters/ba/ba2Bint.wav',
    ),
    WordModel(
      wordToDisplay: 'بِئر',
      wordToCheck: 'بئر',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ba/ba2Bier.png',
      voicePath: 'media/characters/ba/ba2Bier.wav',
    ),
    WordModel(
      wordToDisplay: 'طبِيب',
      wordToCheck: 'طبيب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ba/ba2Tabeeb.png',
      voicePath: 'media/characters/ba/ba2Tabeeb.wav',
    ),
    WordModel(
      wordToDisplay: 'ربِيع',
      wordToCheck: 'ربيع',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ba/ba2Rabie.png',
      voicePath: 'media/characters/ba/ba2Rabie.wav',
    ),
  ],
  'بُ': [
    WordModel(
      wordToDisplay: 'بُومة',
      wordToCheck: 'بومه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ba/ba3Buma.png',
      voicePath: 'media/characters/ba/ba3Buma.wav',
    ),
    WordModel(
      wordToDisplay: 'بُرتقال',
      wordToCheck: 'برتقال',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ba/ba3Burtuqal.png',
      voicePath: 'media/characters/ba/ba3Burtuqal.wav',
    ),
    WordModel(
      wordToDisplay: 'بُرج',
      wordToCheck: 'برج',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ba/ba3Burg.png',
      voicePath: 'media/characters/ba/ba3Burg.wav',
    ),
    WordModel(
      wordToDisplay: 'بُندق',
      wordToCheck: 'بندق',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ba/ba3Bunduq.png',
      voicePath: 'media/characters/ba/ba3Bunduq.wav',
    ),
    WordModel(
      wordToDisplay: 'عنكبُوت',
      wordToCheck: 'عنكبوت',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ba/ba3Ankaboot.png',
      voicePath: 'media/characters/ba/ba3Ankaboot.wav',
    ),
    WordModel(
      wordToDisplay: 'صابُون',
      wordToCheck: 'صابون',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ba/ba3Saboon.png',
      voicePath: 'media/characters/ba/ba3Saboon.wav',
    ),
  ],
  'بْ': [
    WordModel(
      wordToDisplay: 'حبْل',
      wordToCheck: 'حبل',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ba/ba4Habl.png',
      voicePath: 'media/characters/ba/ba4Habl.wav',
    ),
    WordModel(
      wordToDisplay: 'خبْز',
      wordToCheck: 'خبز',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ba/ba4Khubz.png',
      voicePath: 'media/characters/ba/ba4Khubz.wav',
    ),
  ],
},
'ت': {
  'تَ': [
    WordModel(
      wordToDisplay: 'تَاج',
      wordToCheck: 'تاج',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ta/ta1Taaj.png',
      voicePath: 'assets/media/characters/ta/ta1Taaj.wav',
    ),
    WordModel(
      wordToDisplay: 'تَمر',
      wordToCheck: 'تمر',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ta/ta1Tamr.png',
      voicePath: 'assets/media/characters/ta/ta1Tamr.wav',
    ),
    WordModel(
      wordToDisplay: 'فستَان',
      wordToCheck: 'فستان',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ta/ta1Fustaan.png',
      voicePath: 'assets/media/characters/ta/ta1Fustaan.wav',
    ),
    WordModel(
      wordToDisplay: 'مفتَاح',
      wordToCheck: 'مفتاح',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ta/ta1Miftaah.png',
      voicePath: 'assets/media/characters/ta/ta1Miftaah.wav',
    ),
  ],
  'تِ': [
    WordModel(
      wordToDisplay: 'تِمساح',
      wordToCheck: 'تمساح',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ta/ta2Timsah.png',
      voicePath: 'assets/media/characters/ta/ta2Timsah.wav',
    ),
    WordModel(
      wordToDisplay: 'تِين',
      wordToCheck: 'تين',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ta/ta2Teen.png',
      voicePath: 'assets/media/characters/ta/ta2Teen.wav',
    ),
    WordModel(
      wordToDisplay: 'نتِيجة',
      wordToCheck: 'نتيجه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ta/ta2Nateejah.png',
      voicePath: 'assets/media/characters/ta/ta2Nateejah.wav',
    ),
    WordModel(
      wordToDisplay: 'مفاتِيح',
      wordToCheck: 'مفاتيح',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ta/ta2Mafateeha.png',
      voicePath: 'assets/media/characters/ta/ta2Mafateeha.wav',
    ),
  ],
  'تُ': [
    WordModel(
      wordToDisplay: 'تُوت',
      wordToCheck: 'توت',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ta/ta3Toot.png',
      voicePath: 'assets/media/characters/ta/ta3Toot.wav',
    ),
    WordModel(
      wordToDisplay: 'تُفاح',
      wordToCheck: 'تفاح',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ta/ta3Toofah.png',
      voicePath: 'assets/media/characters/ta/ta3Toofah.wav',
    ),
    WordModel(
      wordToDisplay: 'زيتُون',
      wordToCheck: 'زيتون',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ta/ta3Zaytoon.png',
      voicePath: 'assets/media/characters/ta/ta3Zaytoon.wav',
    ),
    WordModel(
      wordToDisplay: 'كتُب',
      wordToCheck: 'كتب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ta/ta3Kutub.png',
      voicePath: 'assets/media/characters/ta/ta3Kutub.wav',
    ),
  ],
  'تْ': [
    WordModel(
      wordToDisplay: 'متْجر',
      wordToCheck: 'متجر',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ta/ta4Matjar.png',
      voicePath: 'assets/media/characters/ta/ta4Matjar.wav',
    ),
    WordModel(
      wordToDisplay: 'كتْكوت',
      wordToCheck: 'كتكوت',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ta/ta4Katkoot.png',
      voicePath: 'assets/media/characters/ta/ta4Katkoot.wav',
    ),
    WordModel(
      wordToDisplay: 'ختْم',
      wordToCheck: 'ختم',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ta/ta4Khtm.png',
      voicePath: 'assets/media/characters/ta/ta4Khtm.wav',
    ),
    WordModel(
      wordToDisplay: 'متْر',
      wordToCheck: 'متر',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ta/ta4Mitr.png',
      voicePath: 'assets/media/characters/ta/ta4Mitr.wav',
    ),
  ],
},
  'ث': {
  'ثَ': [
    WordModel(
      wordToDisplay: 'ثَعلب',
      wordToCheck: 'ثعلب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tha/tha1Thaalab.png',
      voicePath: 'assets/media/characters/tha/tha1Thaalab.wav',
    ),
    WordModel(
      wordToDisplay: 'ثَور',
      wordToCheck: 'ثور',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tha/tha1Thawr.png',
      voicePath: 'assets/media/characters/tha/tha1Thawr.wav',
    ),
    WordModel(
      wordToDisplay: 'ثَلج',
      wordToCheck: 'ثلج',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tha/tha1Thalj.png',
      voicePath: 'assets/media/characters/tha/tha1Thalj.wav',
    ),
    WordModel(
      wordToDisplay: 'ثَوب',
      wordToCheck: 'ثوب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tha/tha1Thawb.png',
      voicePath: 'assets/media/characters/tha/tha1Thawb.wav',
    ),
    WordModel(
      wordToDisplay: 'مثَلجات',
      wordToCheck: 'مثلجات',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tha/tha1Mathalajaat.png',
      voicePath: 'assets/media/characters/tha/tha1Mathalajaat.wav',
    ),
    WordModel(
      wordToDisplay: 'مثَلث',
      wordToCheck: 'مثلث',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tha/tha1Mathalath.png',
      voicePath: 'assets/media/characters/tha/tha1Mathalath.wav',
    ),
  ],
  'ثِ': [
    WordModel(
      wordToDisplay: 'ثِياب',
      wordToCheck: 'ثياب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tha/tha2Thiyab.png',
      voicePath: 'assets/media/characters/tha/tha2Thiyab.wav',
    ),
    WordModel(
      wordToDisplay: 'ثِمار',
      wordToCheck: 'ثمار',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tha/tha2Thimar.png',
      voicePath: 'assets/media/characters/tha/tha2Thimar.wav',
    ),
  ],
  'ثُ': [
    WordModel(
      wordToDisplay: 'ثُعبان',
      wordToCheck: 'ثعبان',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tha/tha3Thuaban.png',
      voicePath: 'assets/media/characters/tha/tha3Thuaban.wav',
    ),
    WordModel(
      wordToDisplay: 'ثُوم',
      wordToCheck: 'ثوم',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tha/tha3Thoom.png',
      voicePath: 'assets/media/characters/tha/tha3Thoom.wav',
    ),
    WordModel(
      wordToDisplay: 'ثُقب',
      wordToCheck: 'ثقب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tha/tha3Thuqb.png',
      voicePath: 'assets/media/characters/tha/tha3Thuqb.wav',
    ),
    WordModel(
      wordToDisplay: 'ثُلث',
      wordToCheck: 'ثلث',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tha/tha3Thuluth.png',
      voicePath: 'assets/media/characters/tha/tha3Thuluth.wav',
    ),
  ],
  'ثْ': [
    WordModel(
      wordToDisplay: 'كمثْري',
      wordToCheck: 'كمثري',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tha/tha4Kummathari.png',
      voicePath: 'assets/media/characters/tha/tha4Kummathari.wav',
    ),
    WordModel(
      wordToDisplay: 'أثْقال',
      wordToCheck: 'اثقال',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tha/tha4Athqal.png',
      voicePath: 'assets/media/characters/tha/tha4Athqal.wav',
    ),
  ],
},
'ج': {
  'جَ': [
    WordModel(
      wordToDisplay: 'جَزر',
      wordToCheck: 'جزر',
      imagePadding: 0,
      imagePath: 'assets/media/characters/jeem/jeem1Jazar.png',
      voicePath: 'assets/media/characters/jeem/jeem1Jazar.wav',
    ),
    WordModel(
      wordToDisplay: 'جَمل',
      wordToCheck: 'جمل',
      imagePadding: 0,
      imagePath: 'assets/media/characters/jeem/jeem1Jamal.png',
      voicePath: 'assets/media/characters/jeem/jeem1Jamal.wav',
    ),
    WordModel(
      wordToDisplay: 'جَرس',
      wordToCheck: 'جرس',
      imagePadding: 0,
      imagePath: 'assets/media/characters/jeem/jeem1Jaras.png',
      voicePath: 'assets/media/characters/jeem/jeem1Jaras.wav',
    ),
    WordModel(
      wordToDisplay: 'جَبل',
      wordToCheck: 'جبل',
      imagePadding: 0,
      imagePath: 'assets/media/characters/jeem/jeem1Jabal.png',
      voicePath: 'assets/media/characters/jeem/jeem1Jabal.wav',
    ),
    WordModel(
      wordToDisplay: 'شجَرة',
      wordToCheck: 'شجره',
      imagePadding: 0,
      imagePath: 'assets/media/characters/jeem/jeem1Shajara.png',
      voicePath: 'assets/media/characters/jeem/jeem1Shajara.wav',
    ),
    WordModel(
      wordToDisplay: 'حجَارة',
      wordToCheck: 'حجاره',
      imagePadding: 0,
      imagePath: 'assets/media/characters/jeem/jeem1Hijara.png',
      voicePath: 'assets/media/characters/jeem/jeem1Hijara.wav',
    ),
  ],
  'جِ': [
    WordModel(
      wordToDisplay: 'جِسر',
      wordToCheck: 'جسر',
      imagePadding: 0,
      imagePath: 'assets/media/characters/jeem/jeem2Jisr.png',
      voicePath: 'assets/media/characters/jeem/jeem2Jisr.wav',
    ),
    WordModel(
      wordToDisplay: 'جِبال',
      wordToCheck: 'جبال',
      imagePadding: 0,
      imagePath: 'assets/media/characters/jeem/jeem2Jibal.png',
      voicePath: 'assets/media/characters/jeem/jeem2Jibal.wav',
    ),
    WordModel(
      wordToDisplay: 'عجِين',
      wordToCheck: 'عجين',
      imagePadding: 0,
      imagePath: 'assets/media/characters/jeem/jeem2Ajeen.png',
      voicePath: 'assets/media/characters/jeem/jeem2Ajeen.wav',
    ),
    WordModel(
      wordToDisplay: 'مسجِد',
      wordToCheck: 'مسجد',
      imagePadding: 0,
      imagePath: 'assets/media/characters/jeem/jeem2Masjid.png',
      voicePath: 'assets/media/characters/jeem/jeem2Masjid.wav',
    ),
  ],
  'جُ': [
    WordModel(
      wordToDisplay: 'جُندي',
      wordToCheck: 'جندى',
      imagePadding: 0,
      imagePath: 'assets/media/characters/jeem/jeem3Jundi.png',
      voicePath: 'assets/media/characters/jeem/jeem3Jundi.wav',
    ),
    WordModel(
      wordToDisplay: 'جُسور',
      wordToCheck: 'جسور',
      imagePadding: 0,
      imagePath: 'assets/media/characters/jeem/jeem3Jusoor.png',
      voicePath: 'assets/media/characters/jeem/jeem3Jusoor.wav',
    ),
    WordModel(
      wordToDisplay: 'عجُوز',
      wordToCheck: 'عجوز',
      imagePadding: 0,
      imagePath: 'assets/media/characters/jeem/jeem3Ajooz.png',
      voicePath: 'assets/media/characters/jeem/jeem3Ajooz.wav',
    ),
  
    WordModel(
      wordToDisplay: 'رجُل',
      wordToCheck: 'رجل',
      imagePadding: 0,
      imagePath: 'assets/media/characters/jeem/jeem3Rajul.png',
      voicePath: 'assets/media/characters/jeem/jeem3Rajul.wav',
    ),
  ],
  'جْ': [
    WordModel(
      wordToDisplay: 'نجْم',
      wordToCheck: 'نجم',
      imagePadding: 0,
      imagePath: 'assets/media/characters/jeem/jeem4Najm.png',
      voicePath: 'assets/media/characters/jeem/jeem4Najm.wav',
    ),
    WordModel(
      wordToDisplay: 'وجْه',
      wordToCheck: 'وجه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/jeem/jeem4Wajh.png',
      voicePath: 'assets/media/characters/jeem/jeem4Wajh.wav',
    ),
    WordModel(
      wordToDisplay: 'فجْل',
      wordToCheck: 'فجل',
      imagePadding: 0,
      imagePath: 'assets/media/characters/jeem/jeem4Fijl.png',
      voicePath: 'assets/media/characters/jeem/jeem4Fijl.wav',
    ),
    WordModel(
      wordToDisplay: 'رجْل',
      wordToCheck: 'رجل',
      imagePadding: 0,
      imagePath: 'assets/media/characters/jeem/jeem4Rijl.png',
      voicePath: 'assets/media/characters/jeem/jeem4Rijl.wav',
    ),
  ],
},
'ح': {
  'حَ': [
    WordModel(
      wordToDisplay: 'حَبل',
      wordToCheck: 'حبل',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ha/ha1Habl.png',
      voicePath: 'assets/media/characters/ha/ha1Habl.wav',
    ),
    WordModel(
      wordToDisplay: 'حَريق',
      wordToCheck: 'حريق',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ha/ha1Hareeq.png',
      voicePath: 'assets/media/characters/ha/ha1Hareeq.wav',
    ),
    WordModel(
      wordToDisplay: 'حَلوي',
      wordToCheck: 'حلوى',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ha/ha1Halwa.png',
      voicePath: 'assets/media/characters/ha/ha1Halwa.wav',
    ),
    WordModel(
      wordToDisplay: 'حَائط',
      wordToCheck: 'حائط',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ha/ha1Hayt.png',
      voicePath: 'assets/media/characters/ha/ha1Hayt.wav',
    ),
    WordModel(
      wordToDisplay: 'تفاحَة',
      wordToCheck: 'تفاحه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ha/ha1Tuffaha.png',
      voicePath: 'assets/media/characters/ha/ha1Tuffaha.wav',
    ),
    WordModel(
      wordToDisplay: 'ممحَاه',
      wordToCheck: 'ممحاه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ha/ha1Mimha.png',
      voicePath: 'assets/media/characters/ha/ha1Mimha.wav',
    ),
  ],
  'حِ': [
    WordModel(
      wordToDisplay: 'حِصان',
      wordToCheck: 'حصان',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ha/ha2Hisan.png',
      voicePath: 'assets/media/characters/ha/ha2Hisan.wav',
    ),
    WordModel(
      wordToDisplay: 'حِذاء',
      wordToCheck: 'حذاء',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ha/ha2Hida.png',
      voicePath: 'assets/media/characters/ha/ha2Hida.wav',
    ),
    WordModel(
      wordToDisplay: 'شاحِنة',
      wordToCheck: 'شاحنه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ha/ha2Shahina.png',
      voicePath: 'assets/media/characters/ha/ha2Shahina.wav',
    ),
    WordModel(
      wordToDisplay: 'نحِيف',
      wordToCheck: 'نحيف',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ha/ha2Naheef.png',
      voicePath: 'assets/media/characters/ha/ha2Naheef.wav',
    ),
  ],
  'حُ': [
    WordModel(
      wordToDisplay: 'حُوت',
      wordToCheck: 'حوت',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ha/ha3Hoot.png',
      voicePath: 'assets/media/characters/ha/ha3Hoot.wav',
    ),
    WordModel(
      wordToDisplay: 'حُلم',
      wordToCheck: 'حلم',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ha/ha3Hulm.png',
      voicePath: 'assets/media/characters/ha/ha3Hulm.wav',
    ),
    WordModel(
      wordToDisplay: 'لحُوم',
      wordToCheck: 'لحوم',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ha/ha3Lohoom.png',
      voicePath: 'assets/media/characters/ha/ha3Lohoom.wav',
    ),
    WordModel(
      wordToDisplay: 'بحُور',
      wordToCheck: 'بحور',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ha/ha3Bohoor.png',
      voicePath: 'assets/media/characters/ha/ha3Bohoor.wav',
    ),
  ],
  'حْ': [
    WordModel(
      wordToDisplay: 'نحْله',
      wordToCheck: 'نحله',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ha/ha4Nahla.png',
      voicePath: 'assets/media/characters/ha/ha4Nahla.wav',
    ),
    WordModel(
      wordToDisplay: 'صحْن',
      wordToCheck: 'صحن',
      imagePadding: 0,
      imagePath: 'assets/media/characters/ha/ha4Sahn.png',
      voicePath: 'assets/media/characters/ha/ha4Sahn.wav',
    ),
  ],
},
'خ': {
  'خَ': [
    WordModel(
      wordToDisplay: 'خَروف',
      wordToCheck: 'خروف',
      imagePadding: 0,
      imagePath: 'assets/media/characters/khaa/khaa1Kharouf.png',
      voicePath: 'media/characters/khaa/khaa1Kharouf.wav',
    ),
    WordModel(
      wordToDisplay: 'خَاتم',
      wordToCheck: 'خاتم',
      imagePadding: 0,
      imagePath: 'assets/media/characters/khaa/khaa1Khaatim.png',
      voicePath: 'media/characters/khaa/khaa1Khaatim.wav',
    ),
    WordModel(
      wordToDisplay: 'مخَالب',
      wordToCheck: 'مخالب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/khaa/khaa1Makhalaab.png',
      voicePath: 'media/characters/khaa/khaa1Makhalaab.wav',
    ),
    WordModel(
      wordToDisplay: 'أخَذ',
      wordToCheck: 'اخذ',
      imagePadding: 0,
      imagePath: 'assets/media/characters/khaa/khaa1Akhath.png',
      voicePath: 'media/characters/khaa/khaa1Akhath.wav',
    ),
  ],
  'خِ': [
    WordModel(
      wordToDisplay: 'خِيار',
      wordToCheck: 'خيار',
      imagePadding: 0,
      imagePath: 'assets/media/characters/khaa/khaa2Khiar.png',
      voicePath: 'media/characters/khaa/khaa2Khiar.wav',
    ),
    WordModel(
      wordToDisplay: 'خِزانة',
      wordToCheck: 'خزانه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/khaa/khaa2Kizaanah.png',
      voicePath: 'media/characters/khaa/khaa2Kizaanah.wav',
    ),
    WordModel(
      wordToDisplay: 'باخِرة',
      wordToCheck: 'باخره',
      imagePadding: 0,
      imagePath: 'assets/media/characters/khaa/khaa2Bakhera.png',
      voicePath: 'media/characters/khaa/khaa2Bakhera.wav',
    ),
    WordModel(
      wordToDisplay: 'ساخِن',
      wordToCheck: 'ساخن',
      imagePadding: 0,
      imagePath: 'assets/media/characters/khaa/khaa2Saakhen.png',
      voicePath: 'media/characters/khaa/khaa2Saakhen.wav',
    ),
  ],
  'خُ': [
    WordModel(
      wordToDisplay: 'خُبز',
      wordToCheck: 'خبز',
      imagePadding: 0,
      imagePath: 'assets/media/characters/khaa/khaa3Khubz.png',
      voicePath: 'media/characters/khaa/khaa3Khubz.wav',
    ),
    WordModel(
      wordToDisplay: 'خُفاش',
      wordToCheck: 'خفاش',
      imagePadding: 0,
      imagePath: 'assets/media/characters/khaa/khaa3Khofaash.png',
      voicePath: 'media/characters/khaa/khaa3Khofaash.wav',
    ),
    WordModel(
      wordToDisplay: 'بخُور',
      wordToCheck: 'بخور',
      imagePadding: 0,
      imagePath: 'assets/media/characters/khaa/khaa3Bakhoor.png',
      voicePath: 'media/characters/khaa/khaa3Bakhoor.wav',
    ),
    WordModel(
      wordToDisplay: 'خُنفساء',
      wordToCheck: 'خنفساء',
      imagePadding: 0,
      imagePath: 'assets/media/characters/khaa/khaa3Khunfusa.png',
      voicePath: 'media/characters/khaa/khaa3Khunfusa.wav',
    ),
  ],
  'خْ': [
    WordModel(
      wordToDisplay: 'نْخل',
      wordToCheck: 'نخل',
      imagePadding: 0,
      imagePath: 'assets/media/characters/khaa/khaa4Nakhl.png',
      voicePath: 'media/characters/khaa/khaa4Nakhl.wav',
    ),
    WordModel(
      wordToDisplay: 'صخْره',
      wordToCheck: 'صخره',
      imagePadding: 0,
      imagePath: 'assets/media/characters/khaa/khaa4Sakhrah.png',
      voicePath: 'media/characters/khaa/khaa4Sakhrah.wav',
    ),
  ],
},
'د': {
  'دَ': [
    WordModel(
      wordToDisplay: 'دَلو',
      wordToCheck: 'دلو',
      imagePadding: 0,
      imagePath: 'assets/media/characters/daal/daal1Dalou.png',
      voicePath: 'media/characters/daal/daal1Dalou.wav',
    ),
    WordModel(
      wordToDisplay: 'دَجاجه',
      wordToCheck: 'دجاجه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/daal/daal1Dajaaja.png',
      voicePath: 'media/characters/daal/daal1Dajaaja.wav',
    ),
    WordModel(
      wordToDisplay: 'وردَة',
      wordToCheck: 'ورده',
      imagePadding: 0,
      imagePath: 'assets/media/characters/daal/daal1Wardah.png',
      voicePath: 'media/characters/daal/daal1Wardah.wav',
    ),
    WordModel(
      wordToDisplay: 'ميدَاليه',
      wordToCheck: 'ميداليه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/daal/daal1Midaalyah.png',
      voicePath: 'media/characters/daal/daal1Midaalyah.wav',
    ),
  ],
  'دِ': [
    WordModel(
      wordToDisplay: 'دِيك',
      wordToCheck: 'ديك',
      imagePadding: 0,
      imagePath: 'assets/media/characters/daal/daal2Deek.png',
      voicePath: 'media/characters/daal/daal2Deek.wav',
    ),
    WordModel(
      wordToDisplay: 'دِرع',
      wordToCheck: 'درع',
      imagePadding: 0,
      imagePath: 'assets/media/characters/daal/daal2Dir3.png',
      voicePath: 'media/characters/daal/daal2Dir3.wav',
    ),
    WordModel(
      wordToDisplay: 'صدِيق',
      wordToCheck: 'صديق',
      imagePadding: 0,
      imagePath: 'assets/media/characters/daal/daal2Sadeeq.png',
      voicePath: 'media/characters/daal/daal2Sadeeq.wav',
    ),
    WordModel(
      wordToDisplay: 'حدِيد',
      wordToCheck: 'حديد',
      imagePadding: 0,
      imagePath: 'assets/media/characters/daal/daal2Hadeed.png',
      voicePath: 'media/characters/daal/daal2Hadeed.wav',
    ),
  ],
  'دُ': [
    WordModel(
      wordToDisplay: 'دُلفين',
      wordToCheck: 'دلفين',
      imagePadding: 0,
      imagePath: 'assets/media/characters/daal/daal3Dolfen.png',
      voicePath: 'media/characters/daal/daal3Dolfen.wav',
    ),
    WordModel(
      wordToDisplay: 'دُمية',
      wordToCheck: 'دميه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/daal/daal3Domya.png',
      voicePath: 'media/characters/daal/daal3Domya.wav',
    ),
    WordModel(
      wordToDisplay: 'صندُوق',
      wordToCheck: 'صندوق',
      imagePadding: 0,
      imagePath: 'assets/media/characters/daal/daal3Sandook.png',
      voicePath: 'media/characters/daal/daal3Sandook.wav',
    ),
    WordModel(
      wordToDisplay: 'دُودة',
      wordToCheck: 'دوده',
      imagePadding: 0,
      imagePath: 'assets/media/characters/daal/daal3Dooda.png',
      voicePath: 'media/characters/daal/daal3Dooda.wav',
    ),
  ],
  'دْ': [
    WordModel(
      wordToDisplay: 'مدْفع',
      wordToCheck: 'مدفع',
      imagePadding: 0,
      imagePath: 'assets/media/characters/daal/daal4Madfa.png',
      voicePath: 'media/characters/daal/daal4Madfa.wav',
    ),
    WordModel(
      wordToDisplay: 'خدْعة',
      wordToCheck: 'خدعه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/daal/daal4Khadaa.png',
      voicePath: 'media/characters/daal/daal4Khadaa.wav',
    ),
    WordModel(
      wordToDisplay: 'مدْرسة',
      wordToCheck: 'مدرسه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/daal/daal4Madrasa.png',
      voicePath: 'media/characters/daal/daal4Madrasa.wav',
    ),
    WordModel(
      wordToDisplay: 'هدْهد',
      wordToCheck: 'هدهد',
      imagePadding: 0,
      imagePath: 'assets/media/characters/daal/daal4Hudhud.png',
      voicePath: 'media/characters/daal/daal4Hudhud.wav',
    ),
  ],
},
'ذ': {
  'ذَ': [
    WordModel(
      wordToDisplay: 'ذَيل',
      wordToCheck: 'ذيل',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thal/thal1Thail.png',
      voicePath: 'media/characters/thal/thal1Thail.wav',
    ),
    WordModel(
      wordToDisplay: 'ذَهب',
      wordToCheck: 'ذهب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thal/thal1Thahab.png',
      voicePath: 'media/characters/thal/thal1Thahab.wav',
    ),
    WordModel(
      wordToDisplay: 'حذَاء',
      wordToCheck: 'حذاء',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thal/thal1Hithaa.png',
      voicePath: 'media/characters/thal/thal1Hithaa.wav',
    ),
    WordModel(
      wordToDisplay: 'نافذَة',
      wordToCheck: 'نافذه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thal/thal1Naafitha.png',
      voicePath: 'media/characters/thal/thal1Naafitha.wav',
    ),
  ],
  'ذِ': [
    WordModel(
      wordToDisplay: 'ذِراع',
      wordToCheck: 'ذراع',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thal/thal2Thiraa.png',
      voicePath: 'media/characters/thal/thal2Thiraa.wav',
    ),
    WordModel(
      wordToDisplay: 'ذِئب',
      wordToCheck: 'ذئب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thal/thal2Thiib.png',
      voicePath: 'media/characters/thal/thal2Thiib.wav',
    ),
    WordModel(
      wordToDisplay: 'مذِيع',
      wordToCheck: 'مذيع',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thal/thal2Muthyee.png',
      voicePath: 'media/characters/thal/thal2Muthyee.wav',
    ),
    WordModel(
      wordToDisplay: 'باذِنجان',
      wordToCheck: 'باذنجان',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thal/thal2Baadhinjan.png',
      voicePath: 'media/characters/thal/thal2Baadhinjan.wav',
    ),
  ],
  'ذُ': [
    WordModel(
      wordToDisplay: 'ذُرة',
      wordToCheck: 'ذره',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thal/thal3Thurah.png',
      voicePath: 'media/characters/thal/thal3Thurah.wav',
    ),
    WordModel(
      wordToDisplay: 'ذُبابة',
      wordToCheck: 'ذبابه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thal/thal3Thubaabah.png',
      voicePath: 'media/characters/thal/thal3Thubaabah.wav',
    ),
    WordModel(
      wordToDisplay: 'أذُن',
      wordToCheck: 'اذن',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thal/thal3Uthun.png',
      voicePath: 'media/characters/thal/thal3Uthun.wav',
    ),
    WordModel(
      wordToDisplay: 'بذُور',
      wordToCheck: 'بذور',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thal/thal3Buthoor.png',
      voicePath: 'media/characters/thal/thal3Buthoor.wav',
    ),
  ],
  'ذْ': [
    WordModel(
      wordToDisplay: 'مذْياع',
      wordToCheck: 'مذياع',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thal/thal4Mithyaa.png',
      voicePath: 'media/characters/thal/thal4Mithyaa.wav',
    ),
    WordModel(
      wordToDisplay: 'جذْع',
      wordToCheck: 'جذع',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thal/thal4Jith3.png',
      voicePath: 'media/characters/thal/thal4Jith3.wav',
    ),
  ],
},
'ر': {
  'رَ': [
    WordModel(
      wordToDisplay: 'رَمل',
      wordToCheck: 'رمل',
      imagePadding: 0,
      imagePath: 'assets/media/characters/raa/raa1Raml.png',
      voicePath: 'media/characters/raa/raa1Raml.wav',
    ),
    WordModel(
      wordToDisplay: 'رَاكون',
      wordToCheck: 'راكون',
      imagePadding: 0,
      imagePath: 'assets/media/characters/raa/raa1Rakun.png',
      voicePath: 'media/characters/raa/raa1Rakun.wav',
    ),
    WordModel(
      wordToDisplay: 'سيارَة',
      wordToCheck: 'سياره',
      imagePadding: 0,
      imagePath: 'assets/media/characters/raa/raa1Sayarh.png',
      voicePath: 'media/characters/raa/raa1Sayarh.wav',
    ),
    WordModel(
      wordToDisplay: 'فرَاشة',
      wordToCheck: 'فراشه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/raa/raa1Farasha.png',
      voicePath: 'media/characters/raa/raa1Farasha.wav',
    ),
  ],
  'رِ': [
    WordModel(
      wordToDisplay: 'رِيشة',
      wordToCheck: 'ريشه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/raa/raa2Reesha.png',
      voicePath: 'media/characters/raa/raa2Reesha.wav',
    ),
    WordModel(
      wordToDisplay: 'رِباط',
      wordToCheck: 'رباط',
      imagePadding: 0,
      imagePath: 'assets/media/characters/raa/raa2Ribat.png',
      voicePath: 'media/characters/raa/raa2Ribat.wav',
    ),
    WordModel(
      wordToDisplay: 'قارِب',
      wordToCheck: 'قارب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/raa/raa2Qarib.png',
      voicePath: 'media/characters/raa/raa2Qarib.wav',
    ),
    WordModel(
      wordToDisplay: 'سرِير',
      wordToCheck: 'سرير',
      imagePadding: 0,
      imagePath: 'assets/media/characters/raa/raa2Sareer.png',
      voicePath: 'media/characters/raa/raa2Sareer.wav',
    ),
  ],
  'رُ': [
    WordModel(
      wordToDisplay: 'رُمان',
      wordToCheck: 'رمان',
      imagePadding: 0,
      imagePath: 'assets/media/characters/raa/raa3Rumman.png',
      voicePath: 'media/characters/raa/raa3Rumman.wav',
    ),
    WordModel(
      wordToDisplay: 'رُمح',
      wordToCheck: 'رمح',
      imagePadding: 0,
      imagePath: 'assets/media/characters/raa/raa3Rumah.png',
      voicePath: 'media/characters/raa/raa3Rumah.wav',
    ),
  ],
  'رْ': [
    WordModel(
      wordToDisplay: 'برْج',
      wordToCheck: 'برج',
      imagePadding: 0,
      imagePath: 'assets/media/characters/raa/raa4Burj.png',
      voicePath: 'media/characters/raa/raa4Burj.wav',
    ),
    WordModel(
      wordToDisplay: 'كرْسي',
      wordToCheck: 'كرسى',
      imagePadding: 0,
      imagePath: 'assets/media/characters/raa/raa4Kursi.png',
      voicePath: 'media/characters/raa/raa4Kursi.wav',
    ),
  ],
},
'ز': {
  'زَ': [
    WordModel(
      wordToDisplay: 'زَرافة',
      wordToCheck: 'زرافه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/zaa/zaa1Zarafa.png',
      voicePath: 'media/characters/zaa/zaa1Zarafa.wav',
    ),
    WordModel(
      wordToDisplay: 'زَهرة',
      wordToCheck: 'زهره',
      imagePadding: 0,
      imagePath: 'assets/media/characters/zaa/zaa1Zahra.png',
      voicePath: 'media/characters/zaa/zaa1Zahra.wav',
    ),
    WordModel(
      wordToDisplay: 'ميزَان',
      wordToCheck: 'ميزان',
      imagePadding: 0,
      imagePath: 'assets/media/characters/zaa/zaa1Mizan.png',
      voicePath: 'media/characters/zaa/zaa1Mizan.wav',
    ),
    WordModel(
      wordToDisplay: 'جزَر',
      wordToCheck: 'جزر',
      imagePadding: 0,
      imagePath: 'assets/media/characters/zaa/zaa1Jazar.png',
      voicePath: 'media/characters/zaa/zaa1Jazar.wav',
    ),
  ],
  'زِ': [
    WordModel(
      wordToDisplay: 'زِر',
      wordToCheck: 'زر',
      imagePadding: 0,
      imagePath: 'assets/media/characters/zaa/zaa2Zir.png',
      voicePath: 'media/characters/zaa/zaa2Zir.wav',
    ),
    WordModel(
      wordToDisplay: 'زِحام',
      wordToCheck: 'زحام',
      imagePadding: 0,
      imagePath: 'assets/media/characters/zaa/zaa2Ziham.png',
      voicePath: 'media/characters/zaa/zaa2Ziham.wav',
    ),
    WordModel(
      wordToDisplay: 'منزِل',
      wordToCheck: 'منزل',
      imagePadding: 0,
      imagePath: 'assets/media/characters/zaa/zaa2Manzil.png',
      voicePath: 'media/characters/zaa/zaa2Manzil.wav',
    ),
    WordModel(
      wordToDisplay: 'جزِيرة',
      wordToCheck: 'جزيره',
      imagePadding: 0,
      imagePath: 'assets/media/characters/zaa/zaa2Jazira.png',
      voicePath: 'media/characters/zaa/zaa2Jazira.wav',
    ),
  ],
  'زُ': [
    WordModel(
      wordToDisplay: 'زُهور',
      wordToCheck: 'زهور',
      imagePadding: 0,
      imagePath: 'assets/media/characters/zaa/zaa3Zuhour.png',
      voicePath: 'media/characters/zaa/zaa3Zuhour.wav',
    ),
    WordModel(
      wordToDisplay: 'زُجاجة',
      wordToCheck: 'زجاجه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/zaa/zaa3Zujaja.png',
      voicePath: 'media/characters/zaa/zaa3Zujaja.wav',
    ),
    WordModel(
      wordToDisplay: 'حلزُون',
      wordToCheck: 'حلزون',
      imagePadding: 0,
      imagePath: 'assets/media/characters/zaa/zaa3Halzoon.png',
      voicePath: 'media/characters/zaa/zaa3Halzoon.wav',
    ),
    WordModel(
      wordToDisplay: 'عزُومة',
      wordToCheck: 'عزومه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/zaa/zaa3Azuma.png',
      voicePath: 'media/characters/zaa/zaa3Azuma.wav',
    ),
  ],
  'زْ': [
    WordModel(
      wordToDisplay: 'أزْرار',
      wordToCheck: 'أزرار',
      imagePadding: 0,
      imagePath: 'assets/media/characters/zaa/zaa4Azrar.png',
      voicePath: 'media/characters/zaa/zaa4Azrar.wav',
    ),
    WordModel(
      wordToDisplay: 'أزْرق',
      wordToCheck: 'أزرق',
      imagePadding: 0,
      imagePath: 'assets/media/characters/zaa/zaa4Azraq.png',
      voicePath: 'media/characters/zaa/zaa4Azraq.wav',
    ),
    WordModel(
      wordToDisplay: 'مزْرعة',
      wordToCheck: 'مزرعه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/zaa/zaa4Mazraa.png',
      voicePath: 'media/characters/zaa/zaa4Mazraa.wav',
    ),
    WordModel(
      wordToDisplay: 'قزْم',
      wordToCheck: 'قزم',
      imagePadding: 0,
      imagePath: 'assets/media/characters/zaa/zaa4Qazm.png',
      voicePath: 'media/characters/zaa/zaa4Qazm.wav',
    ),
  ],
},
'س': {
  'سَ': [
    WordModel(
      wordToDisplay: 'سَمكة',
      wordToCheck: 'سمكه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/seen/seen1Samaka.png',
      voicePath: 'media/characters/seen/seen1Samaka.wav',
    ),
    WordModel(
      wordToDisplay: 'سَحاب',
      wordToCheck: 'سحاب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/seen/seen1Sahab.png',
      voicePath: 'media/characters/seen/seen1Sahab.wav',
    ),
    WordModel(
      wordToDisplay: 'مكنسَة',
      wordToCheck: 'مكنسه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/seen/seen1Miknasa.png',
      voicePath: 'media/characters/seen/seen1Miknasa.wav',
    ),
    WordModel(
      wordToDisplay: 'خنفسَاء',
      wordToCheck: 'خنفساء',
      imagePadding: 0,
      imagePath: 'assets/media/characters/seen/seen1Khanfasa.png',
      voicePath: 'media/characters/seen/seen1Khanfasa.wav',
    ),
  ],
  'سِ': [
    WordModel(
      wordToDisplay: 'سِنارة',
      wordToCheck: 'سناره',
      imagePadding: 0,
      imagePath: 'assets/media/characters/seen/seen2Sinara.png',
      voicePath: 'media/characters/seen/seen2Sinara.wav',
    ),
    WordModel(
      wordToDisplay: 'سِمسم',
      wordToCheck: 'سمسم',
      imagePadding: 0,
      imagePath: 'assets/media/characters/seen/seen2Simsim.png',
      voicePath: 'media/characters/seen/seen2Simsim.wav',
    ),
    WordModel(
      wordToDisplay: 'غسِيل',
      wordToCheck: 'غسيل',
      imagePadding: 0,
      imagePath: 'assets/media/characters/seen/seen2Ghasil.png',
      voicePath: 'media/characters/seen/seen2Ghasil.wav',
    ),
  ],
  'سُ': [
    WordModel(
      wordToDisplay: 'سُكر',
      wordToCheck: 'سكر',
      imagePadding: 0,
      imagePath: 'assets/media/characters/seen/seen3Sukar.png',
      voicePath: 'media/characters/seen/seen3Sukar.wav',
    ),
    WordModel(
      wordToDisplay: 'سُور',
      wordToCheck: 'سور',
      imagePadding: 0,
      imagePath: 'assets/media/characters/seen/seen3Sour.png',
      voicePath: 'media/characters/seen/seen3Sour.wav',
    ),
    WordModel(
      wordToDisplay: 'حاسُوب',
      wordToCheck: 'حاسوب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/seen/seen3Hasoub.png',
      voicePath: 'media/characters/seen/seen3Hasoub.wav',
    ),
    WordModel(
      wordToDisplay: 'غسُول',
      wordToCheck: 'غسول',
      imagePadding: 0,
      imagePath: 'assets/media/characters/seen/seen3Ghassoul.png',
      voicePath: 'media/characters/seen/seen3Ghassoul.wav',
    ),
  ],
  'سْ': [
    WordModel(
      wordToDisplay: 'مسْطرة',
      wordToCheck: 'مسطره',
      imagePadding: 0,
      imagePath: 'assets/media/characters/seen/seen4Mistrah.png',
      voicePath: 'media/characters/seen/seen4Mistrah.wav',
    ),
    WordModel(
      wordToDisplay: 'مسْجد',
      wordToCheck: 'مسجد',
      imagePadding: 0,
      imagePath: 'assets/media/characters/seen/seen4Masjid.png',
      voicePath: 'media/characters/seen/seen4Masjid.wav',
    ),
    WordModel(
      wordToDisplay: 'نسْر',
      wordToCheck: 'نسر',
      imagePadding: 0,
      imagePath: 'assets/media/characters/seen/seen4Nasr.png',
      voicePath: 'media/characters/seen/seen4Nasr.wav',
    ),
    WordModel(
      wordToDisplay: 'تسْعة',
      wordToCheck: 'تسعه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/seen/seen4TisAAh.png',
      voicePath: 'media/characters/seen/seen4TisAAh.wav',
    ),
  ],
},
'ش': {
  'شَ': [
    WordModel(
      wordToDisplay: 'شَمس',
      wordToCheck: 'شمس',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sheen/sheen1Shams.png',
      voicePath: 'media/characters/sheen/sheen1Shams.wav',
    ),
    WordModel(
      wordToDisplay: 'شَمعة',
      wordToCheck: 'شمعه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sheen/sheen1ShamAAh.png',
      voicePath: 'media/characters/sheen/sheen1ShamAAh.wav',
    ),
    WordModel(
      wordToDisplay: 'فراشَة',
      wordToCheck: 'فراشه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sheen/sheen1Farasha.png',
      voicePath: 'media/characters/sheen/sheen1Farasha.wav',
    ),
    WordModel(
      wordToDisplay: 'أخشَاب',
      wordToCheck: 'أخشاب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sheen/sheen1Akhshaab.png',
      voicePath: 'media/characters/sheen/sheen1Akhshaab.wav',
    ),
  ],
  'شِ': [
    WordModel(
      wordToDisplay: 'شِراع',
      wordToCheck: 'شراع',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sheen/sheen2Shiraa.png',
      voicePath: 'media/characters/sheen/sheen2Shiraa.wav',
    ),
    WordModel(
      wordToDisplay: 'شِبل',
      wordToCheck: 'شبل',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sheen/sheen2Shibl.png',
      voicePath: 'media/characters/sheen/sheen2Shibl.wav',
    ),
    WordModel(
      wordToDisplay: 'نشِيد',
      wordToCheck: 'نشيد',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sheen/sheen2Nasheed.png',
      voicePath: 'media/characters/sheen/sheen2Nasheed.wav',
    ),
    WordModel(
      wordToDisplay: 'نشِيط',
      wordToCheck: 'نشيط',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sheen/sheen2Nasheet.png',
      voicePath: 'media/characters/sheen/sheen2Nasheet.wav',
    ),
  ],
  'شُ': [
    WordModel(
      wordToDisplay: 'شُوكة',
      wordToCheck: 'شوكه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sheen/sheen3Shoka.png',
      voicePath: 'media/characters/sheen/sheen3Shoka.wav',
    ),
    WordModel(
      wordToDisplay: 'شُعلة',
      wordToCheck: 'شعله',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sheen/sheen3ShuAAla.png',
      voicePath: 'media/characters/sheen/sheen3ShuAAla.wav',
    ),
    WordModel(
      wordToDisplay: 'شُموع',
      wordToCheck: 'شموع',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sheen/sheen3ShumouA.png',
      voicePath: 'media/characters/sheen/sheen3ShumouA.wav',
    ),
    WordModel(
      wordToDisplay: 'شُرطي',
      wordToCheck: 'شرطي',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sheen/sheen3Shorty.png',
      voicePath: 'media/characters/sheen/sheen3Shorty.wav',
    ),
  ],
  'شْ': [
    WordModel(
      wordToDisplay: 'مشْط',
      wordToCheck: 'مشط',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sheen/sheen4Masht.png',
      voicePath: 'media/characters/sheen/sheen4Masht.wav',
    ),
    WordModel(
      wordToDisplay: 'عشْب',
      wordToCheck: 'عشب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sheen/sheen4AAshb.png',
      voicePath: 'media/characters/sheen/sheen4AAshb.wav',
    ),
  ],
},
'ص': {
  'صَ': [
    WordModel(
      wordToDisplay: 'صَبار',
      wordToCheck: 'صبار',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sad/sad1Sabbar.png',
      voicePath: 'media/characters/sad/sad1Sabbar.wav',
    ),
    WordModel(
      wordToDisplay: 'صَقر',
      wordToCheck: 'صقر',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sad/sad1Saqr.png',
      voicePath: 'media/characters/sad/sad1Saqr.wav',
    ),
    WordModel(
      wordToDisplay: 'حصَان',
      wordToCheck: 'حصان',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sad/sad1Hisan.png',
      voicePath: 'media/characters/sad/sad1Hisan.wav',
    ),
    WordModel(
      wordToDisplay: 'بصَل',
      wordToCheck: 'بصل',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sad/sad1Basal.png',
      voicePath: 'media/characters/sad/sad1Basal.wav',
    ),
  ],
  'صِ': [
    WordModel(
      wordToDisplay: 'صِراخ',
      wordToCheck: 'صراخ',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sad/sad2Siraakh.png',
      voicePath: 'media/characters/sad/sad2Siraakh.wav',
    ),
    WordModel(
      wordToDisplay: 'صِينية',
      wordToCheck: 'صينيه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sad/sad2Siniya.png',
      voicePath: 'media/characters/sad/sad2Siniya.wav',
    ),
    WordModel(
      wordToDisplay: 'عصِير',
      wordToCheck: 'عصير',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sad/sad2Aseer.png',
      voicePath: 'media/characters/sad/sad2Aseer.wav',
    ),
    WordModel(
      wordToDisplay: 'قصِير',
      wordToCheck: 'قصير',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sad/sad2Qasir.png',
      voicePath: 'media/characters/sad/sad2Qasir.wav',
    ),
  ],
  'صُ': [
    WordModel(
      wordToDisplay: 'صُورة',
      wordToCheck: 'صوره',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sad/sad3Soora.png',
      voicePath: 'media/characters/sad/sad3Soora.wav',
    ),
    WordModel(
      wordToDisplay: 'صُندوق',
      wordToCheck: 'صندوق',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sad/sad3Sunduq.png',
      voicePath: 'media/characters/sad/sad3Sunduq.wav',
    ),
    WordModel(
      wordToDisplay: 'قصُور',
      wordToCheck: 'قصور',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sad/sad3Qusoor.png',
      voicePath: 'media/characters/sad/sad3Qusoor.wav',
    ),
    WordModel(
      wordToDisplay: 'فصُول',
      wordToCheck: 'فصول',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sad/sad3Fusool.png',
      voicePath: 'media/characters/sad/sad3Fusool.wav',
    ),
  ],
  'صْ': [
    WordModel(
      wordToDisplay: 'مصْنع',
      wordToCheck: 'مصنع',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sad/sad4Masnaa.png',
      voicePath: 'media/characters/sad/sad4Masnaa.wav',
    ),
    WordModel(
      wordToDisplay: 'قصْر',
      wordToCheck: 'قصر',
      imagePadding: 0,
      imagePath: 'assets/media/characters/sad/sad4Qasr.png',
      voicePath: 'media/characters/sad/sad4Qasr.wav',
    ),
  ],
},
'ض': {
  'ضَ': [
    WordModel(
      wordToDisplay: 'ضَابط',
      wordToCheck: 'ضابط',
      imagePadding: 0,
      imagePath: 'assets/media/characters/dhad/dhad1Daabit.png',
      voicePath: 'media/characters/dhad/dhad1Daabit.wav',
    ),
    WordModel(
      wordToDisplay: 'ضَباب',
      wordToCheck: 'ضباب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/dhad/dhad1Dabaab.png',
      voicePath: 'media/characters/dhad/dhad1Dabaab.wav',
    ),
    WordModel(
      wordToDisplay: 'خضَار',
      wordToCheck: 'خضار',
      imagePadding: 0,
      imagePath: 'assets/media/characters/dhad/dhad1Khodar.png',
      voicePath: 'media/characters/dhad/dhad1Khodar.wav',
    ),
    WordModel(
      wordToDisplay: 'عضَلات',
      wordToCheck: 'عضلات',
      imagePadding: 0,
      imagePath: 'assets/media/characters/dhad/dhad1Aadlaat.png',
      voicePath: 'media/characters/dhad/dhad1Aadlaat.wav',
    ),
  ],
  'ضِ': [
    WordModel(
      wordToDisplay: 'ضِلع',
      wordToCheck: 'ضلع',
      imagePadding: 0,
      imagePath: 'assets/media/characters/dhad/dhad2DilAA.png',
      voicePath: 'media/characters/dhad/dhad2DilAA.wav',
    ),
    WordModel(
      wordToDisplay: 'ضِرس',
      wordToCheck: 'ضرس',
      imagePadding: 0,
      imagePath: 'assets/media/characters/dhad/dhad2Dirs.png',
      voicePath: 'media/characters/dhad/dhad2Dirs.wav',
    ),
    WordModel(
      wordToDisplay: 'رضِيع',
      wordToCheck: 'رضيع',
      imagePadding: 0,
      imagePath: 'assets/media/characters/dhad/dhad2Radiya.png',
      voicePath: 'media/characters/dhad/dhad2Radiya.wav',
    ),
    WordModel(
      wordToDisplay: 'مضِيء',
      wordToCheck: 'مضيء',
      imagePadding: 0,
      imagePath: 'assets/media/characters/dhad/dhad2Mudi.png',
      voicePath: 'media/characters/dhad/dhad2Mudi.wav',
    ),
  ],
  'ضُ': [
    WordModel(
      wordToDisplay: 'ضُوء',
      wordToCheck: 'ضوء',
      imagePadding: 0,
      imagePath: 'assets/media/characters/dhad/dhad3Dhwa.png',
      voicePath: 'media/characters/dhad/dhad3Dhwa.wav',
    ),
    WordModel(
      wordToDisplay: 'ضُروس',
      wordToCheck: 'ضروس',
      imagePadding: 0,
      imagePath: 'assets/media/characters/dhad/dhad3Dhuros.png',
      voicePath: 'media/characters/dhad/dhad3Dhuros.wav',
    ),
  ],
  'ضْ': [
    WordModel(
      wordToDisplay: 'مضْرب',
      wordToCheck: 'مضرب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/dhad/dhad4Madrab.png',
      voicePath: 'media/characters/dhad/dhad4Madrab.wav',
    ),
    WordModel(
      wordToDisplay: 'غضْبان',
      wordToCheck: 'غضبان',
      imagePadding: 0,
      imagePath: 'assets/media/characters/dhad/dhad4Ghadbaan.png',
      voicePath: 'media/characters/dhad/dhad4Ghadbaan.wav',
    ),
  ],
},
'ط': {
  'طَ': [
    WordModel(
      wordToDisplay: 'طَاووس',
      wordToCheck: 'طاوس',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tah/tah1Taawoos.png',
      voicePath: 'media/characters/tah/tah1Taawoos.wav',
    ),
    WordModel(
      wordToDisplay: 'طَائرة',
      wordToCheck: 'طائره',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tah/tah1Taira.png',
      voicePath: 'media/characters/tah/tah1Taira.wav',
    ),
    WordModel(
      wordToDisplay: 'قطَار',
      wordToCheck: 'قطار',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tah/tah1Qitar.png',
      voicePath: 'media/characters/tah/tah1Qitar.wav',
    ),
    WordModel(
      wordToDisplay: 'بطَاطس',
      wordToCheck: 'بطاطس',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tah/tah1Batatas.png',
      voicePath: 'media/characters/tah/tah1Batatas.wav',
    ),
  ],
  'طِ': [
    WordModel(
      wordToDisplay: 'طِفل',
      wordToCheck: 'طفل',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tah/tah2Tifl.png',
      voicePath: 'media/characters/tah/tah2Tifl.wav',
    ),
    WordModel(
      wordToDisplay: 'طِلاء',
      wordToCheck: 'طلاء',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tah/tah2Tla.png',
      voicePath: 'media/characters/tah/tah2Tla.wav',
    ),
    WordModel(
      wordToDisplay: 'بطِّيخ',
      wordToCheck: 'بطيخ',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tah/tah2Bateekh.png',
      voicePath: 'media/characters/tah/tah2Bateekh.wav',
    ),
    WordModel(
      wordToDisplay: 'طماطِم',
      wordToCheck: 'طماطم',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tah/tah2Tamatim.png',
      voicePath: 'media/characters/tah/tah2Tamatim.wav',
    ),
  ],
  'طُ': [
    WordModel(
      wordToDisplay: 'طُيور',
      wordToCheck: 'طيور',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tah/tah3Tooyoor.png',
      voicePath: 'media/characters/tah/tah3Tooyoor.wav',
    ),
    WordModel(
      wordToDisplay: 'طُوب',
      wordToCheck: 'طوب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tah/tah3Toob.png',
      voicePath: 'media/characters/tah/tah3Toob.wav',
    ),
    WordModel(
      wordToDisplay: 'أخطُبوط',
      wordToCheck: 'اخطبوط',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tah/tah3Akhtooboot.png',
      voicePath: 'media/characters/tah/tah3Akhtooboot.wav',
    ),
    WordModel(
      wordToDisplay: 'خرطُوم',
      wordToCheck: 'خرطوم',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tah/tah3Khartoom.png',
      voicePath: 'media/characters/tah/tah3Khartoom.wav',
    ),
  ],
  'طْ': [
    WordModel(
      wordToDisplay: 'مطْرقة',
      wordToCheck: 'مطرقه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tah/tah4Mitraka.png',
      voicePath: 'media/characters/tah/tah4Mitraka.wav',
    ),
    WordModel(
      wordToDisplay: 'قطْن',
      wordToCheck: 'قطن',
      imagePadding: 0,
      imagePath: 'assets/media/characters/tah/tah4Qaton.png',
      voicePath: 'media/characters/tah/tah4Qaton.wav',
    ),
  ],
},
'ظ': {
  'ظَ': [
    WordModel(
      wordToDisplay: 'ظَرف',
      wordToCheck: 'ظرف',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thah/thah1Tharaf.png',
      voicePath: 'media/characters/thah/thah1Tharaf.wav',
    ),
    WordModel(
      wordToDisplay: 'ظَبي',
      wordToCheck: 'ظبي',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thah/thah1Thabi.png',
      voicePath: 'media/characters/thah/thah1Thabi.wav',
    ),
    WordModel(
      wordToDisplay: 'محفظَة',
      wordToCheck: 'محفظه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thah/thah1Mahfada.png',
      voicePath: 'media/characters/thah/thah1Mahfada.wav',
    ),
    WordModel(
      wordToDisplay: 'مظَلة',
      wordToCheck: 'مظله',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thah/thah1Mithalla.png',
      voicePath: 'media/characters/thah/thah1Mithalla.wav',
    ),
  ],
  'ظِ': [
    WordModel(
      wordToDisplay: 'ظِفر',
      wordToCheck: 'ظفر',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thah/thah2Thifir.png',
      voicePath: 'media/characters/thah/thah2Thifir.wav',
    ),
    WordModel(
      wordToDisplay: 'ظِل',
      wordToCheck: 'ظل',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thah/thah2Thil.png',
      voicePath: 'media/characters/thah/thah2Thil.wav',
    ),
    WordModel(
      wordToDisplay: 'حظِيرة',
      wordToCheck: 'حظيره',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thah/thah2Hathira.png',
      voicePath: 'media/characters/thah/thah2Hathira.wav',
    ),
    WordModel(
      wordToDisplay: 'وظِيفة',
      wordToCheck: 'وظيفه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thah/thah2Wathifa.png',
      voicePath: 'media/characters/thah/thah2Wathifa.wav',
    ),
  ],
  'ظُ': [
    WordModel(
      wordToDisplay: 'ظُروف',
      wordToCheck: 'ظروف',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thah/thah3Thuroof.png',
      voicePath: 'media/characters/thah/thah3Thuroof.wav',
    ),
    WordModel(
      wordToDisplay: 'محظُوظ',
      wordToCheck: 'محظوظ',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thah/thah3Mahthooz.png',
      voicePath: 'media/characters/thah/thah3Mahthooz.wav',
    ),
  ],
  'ظْ': [
    WordModel(
      wordToDisplay: 'عظْم',
      wordToCheck: 'عظم',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thah/thah4Aatham.png',
      voicePath: 'media/characters/thah/thah4Aatham.wav',
    ),
    WordModel(
      wordToDisplay: 'مظْلم',
      wordToCheck: 'مظلم',
      imagePadding: 0,
      imagePath: 'assets/media/characters/thah/thah4Muthlim.png',
      voicePath: 'media/characters/thah/thah4Muthlim.wav',
    ),
  ],
},
  // 'ع': {},
  // 'غ': {},
  // 'ف': {},
  // 'ق': {},
  // 'ك': {},
  // 'ل': {},
'م': {
  'مَ': [
    WordModel(
      wordToDisplay: 'مَلعب',
      wordToCheck: 'ملعب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/meem/meem1Malab.png',
      voicePath: 'media/characters/meem/meem1Malab.wav',
    ),
    WordModel(
      wordToDisplay: 'مَانجو',
      wordToCheck: 'مانجو',
      imagePadding: 0,
      imagePath: 'assets/media/characters/meem/meem1Mango.png',
      voicePath: 'media/characters/meem/meem1Mango.wav',
    ),
    WordModel(
      wordToDisplay: 'رمَان',
      wordToCheck: 'رمان',
      imagePadding: 0,
      imagePath: 'assets/media/characters/meem/meem1Rumman.png',
      voicePath: 'media/characters/meem/meem1Rumman.wav',
    ),
    WordModel(
      wordToDisplay: 'شمَام',
      wordToCheck: 'شمام',
      imagePadding: 0,
      imagePath: 'assets/media/characters/meem/meem1Shamam.png',
      voicePath: 'media/characters/meem/meem1Shamam.wav',
    ),
  ],
  'مِ': [
    WordModel(
      wordToDisplay: 'مِقص',
      wordToCheck: 'مقص',
      imagePadding: 0,
      imagePath: 'assets/media/characters/meem/meem2Miqas.png',
      voicePath: 'media/characters/meem/meem2Miqas.wav',
    ),
    WordModel(
      wordToDisplay: 'مِكواه',
      wordToCheck: 'مكواه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/meem/meem2Mikwa.png',
      voicePath: 'media/characters/meem/meem2Mikwa.wav',
    ),
    WordModel(
      wordToDisplay: 'أمِيرة',
      wordToCheck: 'اميره',
      imagePadding: 0,
      imagePath: 'assets/media/characters/meem/meem2Amira.png',
      voicePath: 'media/characters/meem/meem2Amira.wav',
    ),
    WordModel(
      wordToDisplay: 'قمِيص',
      wordToCheck: 'قميص',
      imagePadding: 0,
      imagePath: 'assets/media/characters/meem/meem2Qamis.png',
      voicePath: 'media/characters/meem/meem2Qamis.wav',
    ),
  ],
  'مُ': [
    WordModel(
      wordToDisplay: 'مُثلث',
      wordToCheck: 'مثلث',
      imagePadding: 0,
      imagePath: 'assets/media/characters/meem/meem3Muthalath.png',
      voicePath: 'media/characters/meem/meem3Muthalath.wav',
    ),
    WordModel(
      wordToDisplay: 'مُهندس',
      wordToCheck: 'مهندس',
      imagePadding: 0,
      imagePath: 'assets/media/characters/meem/meem3Muhandis.png',
      voicePath: 'media/characters/meem/meem3Muhandis.wav',
    ),
    WordModel(
      wordToDisplay: 'ليمُون',
      wordToCheck: 'ليمون',
      imagePadding: 0,
      imagePath: 'assets/media/characters/meem/meem3Laymoon.png',
      voicePath: 'media/characters/meem/meem3Laymoon.wav',
    ),
    WordModel(
      wordToDisplay: 'شمُوع',
      wordToCheck: 'شموع',
      imagePadding: 0,
      imagePath: 'assets/media/characters/meem/meem3ShumouA.png',
      voicePath: 'media/characters/meem/meem3ShumouA.wav',
    ),
  ],
  'مْ': [
    WordModel(
      wordToDisplay: 'شمْس',
      wordToCheck: 'شمس',
      imagePadding: 0,
      imagePath: 'assets/media/characters/meem/meem4Shams.png',
      voicePath: 'media/characters/meem/meem4Shams.wav',
    ),
    WordModel(
      wordToDisplay: 'شمْع',
      wordToCheck: 'شمع',
      imagePadding: 0,
      imagePath: 'assets/media/characters/meem/meem4ShamAA.png',
      voicePath: 'media/characters/meem/meem4ShamAA.wav',
    ),
  ],
},
'ن': {
  'نَ': [
    WordModel(
      wordToDisplay: 'نَار',
      wordToCheck: 'نار',
      imagePadding: 0,
      imagePath: 'assets/media/characters/noon/noon1Naar.png',
      voicePath: 'media/characters/noon/noon1Naar.wav',
    ),
    WordModel(
      wordToDisplay: 'نَخلة',
      wordToCheck: 'نخله',
      imagePadding: 0,
      imagePath: 'assets/media/characters/noon/noon1Nakhlah.png',
      voicePath: 'media/characters/noon/noon1Nakhlah.wav',
    ),
    WordModel(
      wordToDisplay: 'عنَب',
      wordToCheck: 'عنب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/noon/noon1Ainab.png',
      voicePath: 'media/characters/noon/noon1Ainab.wav',
    ),
    WordModel(
      wordToDisplay: 'منَارة',
      wordToCheck: 'مناره',
      imagePadding: 0,
      imagePath: 'assets/media/characters/noon/noon1Manaarah.png',
      voicePath: 'media/characters/noon/noon1Manaarah.wav',
    ),
  ],
  'نِ': [
    WordModel(
      wordToDisplay: 'نِسر',
      wordToCheck: 'نسر',
      imagePadding: 0,
      imagePath: 'assets/media/characters/noon/noon2Nisr.png',
      voicePath: 'media/characters/noon/noon2Nisr.wav',
    ),
    WordModel(
      wordToDisplay: 'نِساء',
      wordToCheck: 'نساء',
      imagePadding: 0,
      imagePath: 'assets/media/characters/noon/noon2Nisaa.png',
      voicePath: 'media/characters/noon/noon2Nisaa.wav',
    ),
    WordModel(
      wordToDisplay: 'أنِيق',
      wordToCheck: 'انِيق',
      imagePadding: 0,
      imagePath: 'assets/media/characters/noon/noon2Aniq.png',
      voicePath: 'media/characters/noon/noon2Aniq.wav',
    ),
    WordModel(
      wordToDisplay: 'جنِين',
      wordToCheck: 'جنين',
      imagePadding: 0,
      imagePath: 'assets/media/characters/noon/noon2Janin.png',
      voicePath: 'media/characters/noon/noon2Janin.wav',
    ),
  ],
  'نُ': [
    WordModel(
      wordToDisplay: 'نُجوم',
      wordToCheck: 'نجوم',
      imagePadding: 0,
      imagePath: 'assets/media/characters/noon/noon3Nujum.png',
      voicePath: 'media/characters/noon/noon3Nujum.wav',
    ),
    WordModel(
      wordToDisplay: 'نُمور',
      wordToCheck: 'نمور',
      imagePadding: 0,
      imagePath: 'assets/media/characters/noon/noon3Numur.png',
      voicePath: 'media/characters/noon/noon3Numur.wav',
    ),
    WordModel(
      wordToDisplay: 'فانُوس',
      wordToCheck: 'فانوس',
      imagePadding: 0,
      imagePath: 'assets/media/characters/noon/noon3Fanous.png',
      voicePath: 'media/characters/noon/noon3Fanous.wav',
    ),
    WordModel(
      wordToDisplay: 'جنُود',
      wordToCheck: 'جنود',
      imagePadding: 0,
      imagePath: 'assets/media/characters/noon/noon3Junood.png',
      voicePath: 'media/characters/noon/noon3Junood.wav',
    ),
  ],
  'نْ': [
    WordModel(
      wordToDisplay: 'سنْجاب',
      wordToCheck: 'سنجاب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/noon/noon4Sinjab.png',
      voicePath: 'media/characters/noon/noon4Sinjab.wav',
    ),
    WordModel(
      wordToDisplay: 'أنْف',
      wordToCheck: 'انف',
      imagePadding: 0,
      imagePath: 'assets/media/characters/noon/noon4Anf.png',
      voicePath: 'media/characters/noon/noon4Anf.wav',
    ),
  ],
},
'ه': {
  'هَ': [
    WordModel(
      wordToDisplay: 'هَاتف',
      wordToCheck: 'هاتف',
      imagePadding: 0,
      imagePath: 'assets/media/characters/haa/haa1Haatif.png',
      voicePath: 'media/characters/haa/haa1Haatif.wav',
    ),
    WordModel(
      wordToDisplay: 'هَرم',
      wordToCheck: 'هرم',
      imagePadding: 0,
      imagePath: 'assets/media/characters/haa/haa1Haram.png',
      voicePath: 'media/characters/haa/haa1Haram.wav',
    ),
    WordModel(
      wordToDisplay: 'فاكهَة',
      wordToCheck: 'فاكهه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/haa/haa1Fakiha.png',
      voicePath: 'media/characters/haa/haa1Fakiha.wav',
    ),
    WordModel(
      wordToDisplay: 'أزهَار',
      wordToCheck: 'ازهار',
      imagePadding: 0,
      imagePath: 'assets/media/characters/haa/haa1Azhaar.png',
      voicePath: 'media/characters/haa/haa1Azhaar.wav',
    ),
  ],
  'هِ': [
    WordModel(
      wordToDisplay: 'هِلال',
      wordToCheck: 'هلال',
      imagePadding: 0,
      imagePath: 'assets/media/characters/haa/haa2Hilal.png',
      voicePath: 'media/characters/haa/haa2Hilal.wav',
    ),
    WordModel(
      wordToDisplay: 'هِرة',
      wordToCheck: 'هره',
      imagePadding: 0,
      imagePath: 'assets/media/characters/haa/haa2Hira.png',
      voicePath: 'media/characters/haa/haa2Hira.wav',
    ),
    WordModel(
      wordToDisplay: 'لهِيب',
      wordToCheck: 'لهيب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/haa/haa2Lahib.png',
      voicePath: 'media/characters/haa/haa2Lahib.wav',
    ),
    WordModel(
      wordToDisplay: 'فهِم',
      wordToCheck: 'فهم',
      imagePadding: 0,
      imagePath: 'assets/media/characters/haa/haa2Fahim.png',
      voicePath: 'media/characters/haa/haa2Fahim.wav',
    ),
  ],
  'هُ': [
    WordModel(
      wordToDisplay: 'هُدهد',
      wordToCheck: 'هدهد',
      imagePadding: 0,
      imagePath: 'assets/media/characters/haa/haa3Hudhud.png',
      voicePath: 'media/characters/haa/haa3Hudhud.wav',
    ),
    WordModel(
      wordToDisplay: 'هُجوم',
      wordToCheck: 'هجوم',
      imagePadding: 0,
      imagePath: 'assets/media/characters/haa/haa3Hujum.png',
      voicePath: 'media/characters/haa/haa3Hujum.wav',
    ),
    WordModel(
      wordToDisplay: 'كهُوف',
      wordToCheck: 'كهوف',
      imagePadding: 0,
      imagePath: 'assets/media/characters/haa/haa3Kuhuf.png',
      voicePath: 'media/characters/haa/haa3Kuhuf.wav',
    ),
    WordModel(
      wordToDisplay: 'زهُور',
      wordToCheck: 'زهور',
      imagePadding: 0,
      imagePath: 'assets/media/characters/haa/haa3Zuhour.png',
      voicePath: 'media/characters/haa/haa3Zuhour.wav',
    ),
  ],
  'هْ': [
    WordModel(
      wordToDisplay: 'فهْد',
      wordToCheck: 'فهد',
      imagePadding: 0,
      imagePath: 'assets/media/characters/haa/haa4Fahd.png',
      voicePath: 'media/characters/haa/haa4Fahd.wav',
    ),
    WordModel(
      wordToDisplay: 'كهْف',
      wordToCheck: 'كهف',
      imagePadding: 0,
      imagePath: 'assets/media/characters/haa/haa4Kahf.png',
      voicePath: 'media/characters/haa/haa4Kahf.wav',
    ),
  ],
},
'و': {
  'وَ': [
    WordModel(
      wordToDisplay: 'وَردة',
      wordToCheck: 'ورده',
      imagePadding: 0,
      imagePath: 'assets/media/characters/waw/waw1Warda.png',
      voicePath: 'media/characters/waw/waw1Warda.wav',
    ),
    WordModel(
      wordToDisplay: 'وَجه',
      wordToCheck: 'وجه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/waw/waw1Wajh.png',
      voicePath: 'media/characters/waw/waw1Wajh.wav',
    ),
    WordModel(
      wordToDisplay: 'ألوَان',
      wordToCheck: 'الوان',
      imagePadding: 0,
      imagePath: 'assets/media/characters/waw/waw1Alwan.png',
      voicePath: 'media/characters/waw/waw1Alwan.wav',
    ),
    WordModel(
      wordToDisplay: 'إوَزة',
      wordToCheck: 'اوزه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/waw/waw1Izza.png',
      voicePath: 'media/characters/waw/waw1Izza.wav',
    ),
  ],
  'وِ': [
    WordModel(
      wordToDisplay: 'وِسادة',
      wordToCheck: 'وساده',
      imagePadding: 0,
      imagePath: 'assets/media/characters/waw/waw2Wisada.png',
      voicePath: 'media/characters/waw/waw2Wisada.wav',
    ),
    WordModel(
      wordToDisplay: 'وِشاح',
      wordToCheck: 'وشاح',
      imagePadding: 0,
      imagePath: 'assets/media/characters/waw/waw2Wishah.png',
      voicePath: 'media/characters/waw/waw2Wishah.wav',
    ),
    WordModel(
      wordToDisplay: 'مصوِر',
      wordToCheck: 'مصور',
      imagePadding: 0,
      imagePath: 'assets/media/characters/waw/waw2Masweer.png',
      voicePath: 'media/characters/waw/waw2Masweer.wav',
    ),
    WordModel(
      wordToDisplay: 'أدوِية',
      wordToCheck: 'ادويه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/waw/waw2Adwia.png',
      voicePath: 'media/characters/waw/waw2Adwia.wav',
    ),
  ],
  'وُ': [
    WordModel(
      wordToDisplay: 'وُجوه',
      wordToCheck: 'وجوه',
      imagePadding: 0,
      imagePath: 'assets/media/characters/waw/waw3Wojooh.png',
      voicePath: 'media/characters/waw/waw3Wojooh.wav',
    ),
    WordModel(
      wordToDisplay: 'وُرود',
      wordToCheck: 'ورود',
      imagePadding: 0,
      imagePath: 'assets/media/characters/waw/waw3Worood.png',
      voicePath: 'media/characters/waw/waw3Worood.wav',
    ),
    WordModel(
      wordToDisplay: 'طاوُوس',
      wordToCheck: 'طاووس',
      imagePadding: 0,
      imagePath: 'assets/media/characters/waw/waw3Tawoos.png',
      voicePath: 'media/characters/waw/waw3Tawoos.wav',
    ),
    WordModel(
      wordToDisplay: 'وُحوش',
      wordToCheck: 'وحوش',
      imagePadding: 0,
      imagePath: 'assets/media/characters/waw/waw3Wahoosh.png',
      voicePath: 'media/characters/waw/waw3Wahoosh.wav',
    ),
  ],
  'وْ': [
    WordModel(
      wordToDisplay: 'زوْرق',
      wordToCheck: 'زورق',
      imagePadding: 0,
      imagePath: 'assets/media/characters/waw/waw4Zawrq.png',
      voicePath: 'media/characters/waw/waw4Zawrq.wav',
    ),
    WordModel(
      wordToDisplay: 'موْج',
      wordToCheck: 'موج',
      imagePadding: 0,
      imagePath: 'assets/media/characters/waw/waw4Mawg.png',
      voicePath: 'media/characters/waw/waw4Mawg.wav',
    ),
  ],
},
'ي': {
  'يَ': [
    WordModel(
      wordToDisplay: 'يَقطين',
      wordToCheck: 'يقطين',
      imagePadding: 0,
      imagePath: 'assets/media/characters/yaa/yaa1Yaqtin.png',
      voicePath: 'media/characters/yaa/yaa1Yaqtin.wav',
    ),
    WordModel(
      wordToDisplay: 'يَد',
      wordToCheck: 'يد',
      imagePadding: 0,
      imagePath: 'assets/media/characters/yaa/yaa1Yad.png',
      voicePath: 'media/characters/yaa/yaa1Yad.wav',
    ),
    WordModel(
      wordToDisplay: 'خيَار',
      wordToCheck: 'خيار',
      imagePadding: 0,
      imagePath: 'assets/media/characters/yaa/yaa1Khiyaar.png',
      voicePath: 'media/characters/yaa/yaa1Khiyaar.wav',
    ),
    WordModel(
      wordToDisplay: 'سيَّارة',
      wordToCheck: 'سياره',
      imagePadding: 0,
      imagePath: 'assets/media/characters/yaa/yaa1Sayara.png',
      voicePath: 'media/characters/yaa/yaa1Sayara.wav',
    ),
  ],
  'يِ': [
    WordModel(
      wordToDisplay: 'كتيِّب',
      wordToCheck: 'كتيب',
      imagePadding: 0,
      imagePath: 'assets/media/characters/yaa/yaa2Kutayyib.png',
      voicePath: 'media/characters/yaa/yaa2Kutayyib.wav',
    ),
    WordModel(
      wordToDisplay: 'مصايِف',
      wordToCheck: 'مصايف',
      imagePadding: 0,
      imagePath: 'assets/media/characters/yaa/yaa2Masaayif.png',
      voicePath: 'media/characters/yaa/yaa2Masaayif.wav',
    ),
  ],
  'يُ': [
    WordModel(
      wordToDisplay: 'يُوسفي',
      wordToCheck: 'يوسفى',
      imagePadding: 0,
      imagePath: 'assets/media/characters/yaa/yaa3Yousfi.png',
      voicePath: 'media/characters/yaa/yaa3Yousfi.wav',
    ),
    WordModel(
      wordToDisplay: 'يُصلي',
      wordToCheck: 'يصلى',
      imagePadding: 0,
      imagePath: 'assets/media/characters/yaa/yaa3Yusalli.png',
      voicePath: 'media/characters/yaa/yaa3Yusalli.wav',
    ),
  ],
  'يْ': [
    WordModel(
      wordToDisplay: 'عيُون',
      wordToCheck: 'عيون',
      imagePadding: 0,
      imagePath: 'assets/media/characters/yaa/yaa4Uyoon.png',
      voicePath: 'media/characters/yaa/yaa4Uyoon.wav',
    ),
    WordModel(
      wordToDisplay: 'سيُوف',
      wordToCheck: 'سيوف',
      imagePadding: 0,
      imagePath: 'assets/media/characters/yaa/yaa4Suyouf.png',
      voicePath: 'media/characters/yaa/yaa4Suyouf.wav',
    ),
    WordModel(
      wordToDisplay: 'بيْت',
      wordToCheck: 'بيت',
      imagePadding: 0,
      imagePath: 'assets/media/characters/yaa/yaa4Bayt.png',
      voicePath: 'media/characters/yaa/yaa4Bayt.wav',
    ),
    WordModel(
      wordToDisplay: 'ليْمون',
      wordToCheck: 'ليمون',
      imagePadding: 0,
      imagePath: 'assets/media/characters/yaa/yaa4Laymoon.png',
      voicePath: 'media/characters/yaa/yaa4Laymoon.wav',
    ),
  ],
},
};