Map<String, List<String>> puzzelMap = {
  "ع": [
    "assets/puzzle/ain/ain1.jpg",
    "assets/puzzle/ain/ain2.jpg",
    "assets/puzzle/ain/ain3.jpg",
    "assets/puzzle/ain/ain4.jpg",
  ],
  "أ": [
    "assets/puzzle/alef/alef1.jpg",
    "assets/puzzle/alef/alef2.jpg",
    "assets/puzzle/alef/alef3.jpg",
    "assets/puzzle/alef/alef4.jpg",
  ],
  "ب": [
    "assets/puzzle/ba/ba1.jpg",
    "assets/puzzle/ba/ba2.jpg",
    "assets/puzzle/ba/ba3.jpg",
    "assets/puzzle/ba/ba4.jpg",
  ],
  "د": [
    "assets/puzzle/daal/daal1.jpg",
    "assets/puzzle/daal/daal2.jpg",
    "assets/puzzle/daal/daal3.jpg",
    "assets/puzzle/daal/daal4.jpg",
  ],
  "ض": [
    "assets/puzzle/dad/dad1.jpg",
    "assets/puzzle/dad/dad2.jpg",
    "assets/puzzle/dad/dad3.jpg",
    "assets/puzzle/dad/dad4.jpg",
  ],
  "ف": [
    "assets/puzzle/faa/faa1.jpg",
    "assets/puzzle/faa/faa2.jpg",
    "assets/puzzle/faa/faa3.jpg",
    "assets/puzzle/faa/faa4.jpg",
  ],
  "غ": [
    "assets/puzzle/ghain/ghain1.jpg",
    "assets/puzzle/ghain/ghain2.jpg",
    "assets/puzzle/ghain/ghain3.jpg",
    "assets/puzzle/ghain/ghain4.jpg",
  ],
  "ه": [
    "assets/puzzle/h/h1.jpg",
    "assets/puzzle/h/h2.jpg",
    "assets/puzzle/h/h3.jpg",
    "assets/puzzle/h/h4.jpg",
  ],
  "ح": [
    "assets/puzzle/ha/ha1.jpg",
    "assets/puzzle/ha/ha2.jpg",
    "assets/puzzle/ha/ha3.jpg",
    "assets/puzzle/ha/ha4.jpg",
  ],
  "ج": [
    "assets/puzzle/jeem/jeem1.jpg",
    "assets/puzzle/jeem/jeem2.jpg",
    "assets/puzzle/jeem/jeem3.jpg",
    "assets/puzzle/jeem/jeem4.jpg",
  ],
  "ك": [
    "assets/puzzle/kaf/kaf1.jpg",
    "assets/puzzle/kaf/kaf2.jpg",
    "assets/puzzle/kaf/kaf3.jpg",
    "assets/puzzle/kaf/kaf4.jpg",
  ],
  "خ": [
    "assets/puzzle/khaa/khaa1.jpg",
    "assets/puzzle/khaa/khaa2.jpg",
    "assets/puzzle/khaa/khaa3.jpg",
    "assets/puzzle/khaa/khaa4.jpg",
  ],
  "ل": [
    "assets/puzzle/lam/lam1.jpg",
    "assets/puzzle/lam/lam2.jpg",
    "assets/puzzle/lam/lam3.jpg",
    "assets/puzzle/lam/lam4.jpg",
  ],
  "م": [
    "assets/puzzle/meem/meem1.jpg",
    "assets/puzzle/meem/meem2.jpg",
    "assets/puzzle/meem/meem3.jpg",
    "assets/puzzle/meem/meem4.jpg",
  ],
  "ن": [
    "assets/puzzle/noon/noon1.jpg",
    "assets/puzzle/noon/noon2.jpg",
    "assets/puzzle/noon/noon3.jpg",
    "assets/puzzle/noon/noon4.jpg",
  ],
  "ق": [
    "assets/puzzle/qaf/qaf1.jpg",
    "assets/puzzle/qaf/qaf2.jpg",
    "assets/puzzle/qaf/qaf3.jpg",
    "assets/puzzle/qaf/qaf4.jpg",
  ],
  "ر": [
    "assets/puzzle/raa/raa1.jpg",
    "assets/puzzle/raa/raa2.jpg",
    "assets/puzzle/raa/raa3.jpg",
    "assets/puzzle/raa/raa4.jpg",
  ],
  "ص": [
    "assets/puzzle/sad/sad1.jpg",
    "assets/puzzle/sad/sad2.jpg",
    "assets/puzzle/sad/sad3.jpg",
    "assets/puzzle/sad/sad4.jpg",
  ],
  "س": [
    "assets/puzzle/seen/seen1.jpg",
    "assets/puzzle/seen/seen2.jpg",
    "assets/puzzle/seen/seen3.jpg",
    "assets/puzzle/seen/seen4.jpg",
  ],
  "ش": [
    "assets/puzzle/sheen/sheen1.jpg",
    "assets/puzzle/sheen/sheen2.jpg",
    "assets/puzzle/sheen/sheen3.jpg",
    "assets/puzzle/sheen/sheen4.jpg",
  ],
  "ت": [
    "assets/puzzle/ta/ta1.jpg",
    "assets/puzzle/ta/ta2.jpg",
    "assets/puzzle/ta/ta3.jpg",
    "assets/puzzle/ta/ta4.jpg",
  ],
  "ط": [
    "assets/puzzle/tah/tah1.jpg",
    "assets/puzzle/tah/tah2.jpg",
    "assets/puzzle/tah/tah3.jpg",
    "assets/puzzle/tah/tah4.jpg",
  ],
  "ث": [
    "assets/puzzle/tha/tha1.jpg",
    "assets/puzzle/tha/tha2.jpg",
    "assets/puzzle/tha/tha3.jpg",
    "assets/puzzle/tha/tha4.jpg",
  ],
  "ذ": [
    "assets/puzzle/thal/thal1.jpg",
    "assets/puzzle/thal/thal2.jpg",
    "assets/puzzle/thal/thal3.jpg",
    "assets/puzzle/thal/thal4.jpg",
  ],
  "و": [
    "assets/puzzle/waw/waw1.jpg",
    "assets/puzzle/waw/waw2.jpg",
    "assets/puzzle/waw/waw3.jpg",
    "assets/puzzle/waw/waw4.jpg",
  ],
  "ي": [
    "assets/puzzle/yaa/yaa1.jpg",
    "assets/puzzle/yaa/yaa2.jpg",
    "assets/puzzle/yaa/yaa3.jpg",
    "assets/puzzle/yaa/yaa4.jpg",
  ],
  "ز": [
    "assets/puzzle/zaa/zaa1.jpg",
    "assets/puzzle/zaa/zaa2.jpg",
    "assets/puzzle/zaa/zaa3.jpg",
    "assets/puzzle/zaa/zaa4.jpg",
  ],
  "ظ": [
    "assets/puzzle/zah/zah1.jpg",
    "assets/puzzle/zah/zah2.jpg",
    "assets/puzzle/zah/zah3.jpg",
    "assets/puzzle/zah/zah4.jpg",
  ],
};
