
Map<String, String> puzzelCompletedMap = {
  "ع": "assets/puzzle/ain/ain.jpeg",
  "أ": "assets/puzzle/alef/alef.jpeg",
  "ب": "assets/puzzle/ba/ba.jpeg",
  "د": "assets/puzzle/daal/daal.jpeg",
  "ض": "assets/puzzle/dad/dad.jpeg",
  "ف": "assets/puzzle/faa/faa.jpeg",
  "غ": "assets/puzzle/ghain/ghain.jpeg",
  "ه": "assets/puzzle/h/h.jpeg",
  "ح": "assets/puzzle/ha/ha.jpeg",
  "ج": "assets/puzzle/jeem/jeem.jpeg",
  "ك": "assets/puzzle/kaf/kaf.jpeg",
  "خ": "assets/puzzle/khaa/khaa.jpeg",
  "ل": "assets/puzzle/lam/lam.jpeg",
  "م": "assets/puzzle/meem/meem.jpeg",
  "ن": "assets/puzzle/noon/noon.jpeg",
  "ق": "assets/puzzle/qaf/qaf.jpeg",
  "ر": "assets/puzzle/raa/raa.jpeg",
  "ص": "assets/puzzle/sad/sad.jpeg",
  "س": "assets/puzzle/seen/seen.jpeg",
  "ش": "assets/puzzle/sheen/sheen.jpeg",
  "ت": "assets/puzzle/ta/ta.jpeg",
  "ط": "assets/puzzle/tah/tah.jpeg",
  "ث": "assets/puzzle/tha/tha.jpeg",
  "ذ": "assets/puzzle/thal/thal.jpeg",
  "و": "assets/puzzle/waw/waw.jpeg",
  "ي": "assets/puzzle/yaa/yaa.jpeg",
  "ز": "assets/puzzle/zaa/zaa.jpeg",
  "ظ": "assets/puzzle/zah/zah.jpeg",
};
