default_platform(:android)

platform :android do
  desc "Distribute the app to Firebase App Distribution"
  lane :distribute do
    sh "flutter clean"
    sh "flutter build apk --release -t lib/main_production.dart --flavor production --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:601776866310:android:7a8bfcaeed46af97786f87",
      firebase_cli_token: "1//03C5Y-MRM-s6VCgYIARAAGAMSNwF-L9IrGjEp9r19FAS9tUJDFVb5uWrHwnLQYx7i6YrTRadBORtoa120jXYh0090MFUi9v3Kf_0",
      upload_timeout: 600,
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      groups: "testers",
      release_notes: "This is a test for the app distribution",
      testers: "aligad.17611@gmail.com",
    )
  end
end
# "mayae5928@gmail.com","ahmedrenad263@gmail.com" are the testers for the app distribution will be added later.